#!/usr/bin/env bash
# Creates the private CA the app pins and the server certificate Postgres and
# pgbouncer present. Run it once on the operator's machine, then copy
# certs/server.crt and certs/server.key to the server next to docker-compose.yml.
# Keep certs/ca.key off the server: it is only needed to issue a new server cert.
#
#   DB_HOST=<db-host> EXTRA_SANS=DNS:<other-name>,IP:<other-ip> ./gen-certs.sh
#
# Re-running keeps the CA and the issued server cert and only rewrites
# frontend/src/db/db-ca.ts with the CA bundle the app trusts. REISSUE=1 issues
# a new server cert (for example to add a SAN); the CA stays, so what the app
# pins is unchanged.
set -euo pipefail

here="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
repo="$(cd "$here/../.." && pwd)"
certs="$here/certs"
host="${DB_HOST:-}"
extra_sans="${EXTRA_SANS:-}"
openssl_bin="${OPENSSL:-openssl}"

mkdir -p "$certs"
chmod 700 "$certs"
cd "$certs"

if [ ! -f ca.key ]; then
  "$openssl_bin" req -x509 -newkey ec -pkeyopt ec_paramgen_curve:P-256 -pkeyopt ec_param_enc:named_curve -nodes \
    -days 3650 -subj "/CN=The Lens DB Root CA" \
    -addext "basicConstraints=critical,CA:true" \
    -addext "keyUsage=critical,keyCertSign,cRLSign" \
    -keyout ca.key -out ca.crt
  chmod 600 ca.key
  echo "created CA (10 years): certs/ca.crt"
fi

# The server cert is issued once; the copy on the server must stay the one the
# repo knows about. REISSUE=1 makes a new one (new SANs, expiry, or a leak).
if [ ! -f server.crt ] || [ "${REISSUE:-0}" = "1" ]; then
  : "${host:?DB_HOST is required to issue the server cert: the hostname the app connects to}"
  san="DNS:${host},DNS:localhost,IP:127.0.0.1${extra_sans:+,${extra_sans}}"
  "$openssl_bin" req -newkey ec -pkeyopt ec_paramgen_curve:P-256 -pkeyopt ec_param_enc:named_curve -nodes \
    -subj "/CN=${host}" -keyout server.key -out server.csr
  "$openssl_bin" x509 -req -in server.csr -CA ca.crt -CAkey ca.key -CAcreateserial \
    -days 1825 -out server.crt \
    -extfile <(printf 'subjectAltName=%s\nextendedKeyUsage=serverAuth\nkeyUsage=critical,digitalSignature\nbasicConstraints=CA:FALSE\n' "$san")
  rm -f server.csr
  chmod 600 server.key
  echo "issued server cert (5 years) for ${san}: certs/server.crt (copy server.crt and server.key to the server)"
else
  echo "server cert already issued; REISSUE=1 to replace it"
fi

# The app pins this CA. Only the CA goes into the bundle, never the server
# cert, so reissuing the server cert does not change what the app trusts.
ts="$repo/frontend/src/db/db-ca.ts"
{
  cat <<'HEADER'
/**
 * Root CAs the app trusts for the database TLS chain. Generated by
 * infra/db/gen-certs.sh; do not edit by hand. The chain is verified against
 * this bundle with rejectUnauthorized, and the server hostname must match the
 * certificate's SAN, so a URL that points anywhere else fails to connect.
 */

HEADER
  printf 'export const LENSDB_ROOT_CA = `'
  cat ca.crt
  printf '`;\n\n'
  printf 'export const DB_ROOT_CAS = [LENSDB_ROOT_CA];\n'
  printf '\nexport const DB_SSL = { ca: DB_ROOT_CAS, rejectUnauthorized: true };\n'
} > "$ts"
echo "wrote $ts"
