/**
 * Root CAs the app trusts for the database TLS chain. Generated by
 * infra/db/gen-certs.sh; do not edit by hand. The chain is verified against
 * this bundle with rejectUnauthorized, and the server hostname must match the
 * certificate's SAN, so a URL that points anywhere else fails to connect.
 */

export const LENSDB_ROOT_CA = `-----BEGIN CERTIFICATE-----
MIIBoTCCAUegAwIBAgIUSwT/d4QJTPhi+S/jp/HYIx18rcYwCgYIKoZIzj0EAwIw
HjEcMBoGA1UEAwwTVGhlIExlbnMgREIgUm9vdCBDQTAeFw0yNjA5MTMxMDEyMTZa
Fw0zNjA5MTAxMDEyMTZaMB4xHDAaBgNVBAMME1RoZSBMZW5zIERCIFJvb3QgQ0Ew
WTATBgcqhkjOPQIBBggqhkjOPQMBBwNCAASD7qleOuyAhxHMBueJ0mQFLGCEa3iR
e3AXA0qoxdg/mu+RLUnC769nMxACQyzvzNyQtu2NWDIHTINy6ZByQV3xo2MwYTAd
BgNVHQ4EFgQUil6cIIFqUqzxiKskYKe9YLRZZkwwHwYDVR0jBBgwFoAUil6cIIFq
UqzxiKskYKe9YLRZZkwwDwYDVR0TAQH/BAUwAwEB/zAOBgNVHQ8BAf8EBAMCAQYw
CgYIKoZIzj0EAwIDSAAwRQIgKGg8hMHnWJtMYU/buXfmHsKKdA2QYDTEyJlofa5o
mVUCIQDsCW7z1q/7y/An9XSFWa18R7lOGQBcKO9sWHNnbMGnDQ==
-----END CERTIFICATE-----
`;

export const DB_ROOT_CAS = [LENSDB_ROOT_CA];

export const DB_SSL = { ca: DB_ROOT_CAS, rejectUnauthorized: true };
